baseURL = "http://nikkiocrochet.com"
title = "Nikki-O Crochet"
author = "Nicole Olander"
theme = "simple-snipcart-shop"
contentDir = "products"
[params]
  instagram = "nikkio_crochet"
  header = "Welcome to Nikki-O Crochet!"
  description = "We make hats and scarves and things"
  products_title = "Our stuff"
  reviews_title = "Our reviews"
  not_found = "Sorry, but we do not have any products in this category yet."
  categories = [
    "For you",
    "For the home",
    "For the furry friends",
    "For the tiny humans"
  ]
  collage = [
    "/images/collage-1.jpg",
    "/images/collage-2.jpg",
    "/images/collage-3.jpg",
    "/images/collage-8.jpg",
    "/images/collage-7.jpg",
    "/images/collage-4.jpg",
    "/images/collage-5.jpg",
    "/images/collage-6.jpg"
  ]
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  snipcart_key = "MzcyMTAwNGYtYzY3ZC00NmRjLThhMDMtN2NjM2NlMWJhNjMzNjM3MzUzMDQxMjAyMzgwNDky"

[params.special_favicon]
  apple_touch = "/favicon/apple-touch-icon.png"
  fav32 = "/favicon/favicon-32x32.png"
  fav16 = "/favicon/favicon-16x16.png"
  manifest = "/favicon/site.webmanifest"
  mask_icon = "/favicon/safari-pinned-tab.svg"
  mask_icon_color = "#977166"
  theme_color = "#fff"
