baseURL = "http://nikkiocrochet.com"
title = "Nikki-O Crochet"
author = "Nicole Olander"
theme = "marketplace"
contentDir = "products"
[params]
  instagram = "nikkio_crochet"
  description = "We make hats and scarves and things"
  products_title = "Our stuff"
  reviews_title = "Our reviews"
  not_found = "Sorry, but we do not have any products in this category yet."
  categories = [
    "For you",
    "For the home",
    "For the furry friends",
    "For the tiny humans"
  ]
  carousel = [
    "/images/collage-1.jpg",
    "/images/collage-2.jpg",
    "/images/collage-3.jpg",
    "/images/collage-8.jpg",
    "/images/collage-7.jpg",
    "/images/collage-4.jpg",
    "/images/collage-5.jpg",
    "/images/collage-6.jpg"
  ]
  snipcart_key = "MzcyMTAwNGYtYzY3ZC00NmRjLThhMDMtN2NjM2NlMWJhNjMzNjM3MzUzMDQxMjAyMzgwNDky"
